CREATE TABLE IF NOT EXISTS migrations (
 id INTEGER PRIMARY KEY,
 timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscribers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  email TEXT
);

INSERT INTO migrations (timestamp) VALUES ('2019-07-15 14:46:38');
