CREATE TABLE IF NOT EXISTS migrations (
 id INTEGER PRIMARY KEY,
 timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscribers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  email TEXT
);
